.TH TLE 1
.SH NAME
tle \- NORAD two-line element set processor
.SH SYNOPSIS
.PP
.B tle COMMAND [ARGUMENT(S)]
.SH DESCRIPTION
.PP
.B tle
is a tool for handling NORAD two-line element sets (TLEs). It can retrieve
the TLE for any satellite specified by NORAD SATNO or international designator. It can also print human-readable elements and compute the epoch time and age of any TLE.
.SH COMMANDS
.TP
.B tle sat [ID]
Return the TLE of the satellite specified by ID, which can be a SATNO (5-digit NORAD catalog ID #, e.g. 25544 for the International Space Station)
or INTDES (International Designator of the form YYNNNA... e.g. 98067A for the ISS). SATNOs with fewer than 5 significant digits must be padded with
zeros, e.g. 00005.
.TP
.B tle decode [ID]
Print a more human-readable list of orbital elements.
.TP
.B tle epochtime [ID]
Print the epoch time of the given TLE in YYYY DDD HH:MM:SS.MMM format.
.TP
.B tle age [ID]
Print the age of the TLE (time elapsed since epoch.)
.TP
.B tle places [PLACE | edit]
If PLACE is a place code found in share/places.csv, print information about the
place. If the argument 'edit' is passed, opens places.csv in $EDITOR.
.TP
.B tle cron
Set up and manage cron jobs for automatically downloading new TLE files.
(Coming soon)
.TP
.B tle looks [ID]
Calculate look angles for a specific satellite. (Coming soon)
.TP
.B tle update
Queries space-track.org to update your local copy of the spacetrack catalog, found at /usr/local/share/tle/tle. Will prompt you for your space-track.org username and password.
.SH EXAMPLES
.TP
.B tle sat 25544
Will print the two-line element set for the International Space Station to stdout.
.TP
.B tle decode 25544
Will print a human-readable list of the ISS's orbital elements.
.TP
.B grep \(dqInclination\(rs|Period\(dq <<< `tle decode 25544`
Since the inputs and outputs of
.B tle
are simply text streams, you can filter them with your built-in utilities such as
.B grep, awk, sort,
etc. This example will show the inclination and period of the ISS. You can write a wrapper script to filter output from
.B tle
in this way for any criteria you may need. 
.TP
.B tle places fyl
Will print information about the RAF Fylingdales radar station: one of the pre-set places for computing look angles in share/places.csv.
.SH AUTHOR
Written by Ray Patrick <ray@raypatrick.xyz> in 2020.
.SH LICENSE
GPLv3
.SH SEE ALSO
.B bc(1), curl(1), grep(1), sed(1)
